import { DimensionsWcInterface } from './dimensions-wc.interface';
import { CategoryWcInterface } from './category-wc.interface';
import { ImageWcInterface } from './image-wc.interface';
import { LinksWcInterface } from './links-wc.interface';
import { MetaDataWcInterface } from './meta-data-wc.interface';
import { AttributeWcInterface } from './attribute-wc.interface';
import { VariationWcInterface } from './variation-wc.interface';
import { TagWcInterface } from './tag-wc.interface';

export interface ProductWcInterface {
    id?: number;
    name: string;
    slug?: string;
    permalink?: string;
    date_created?: string;
    date_created_gmt?: string;
    date_modified?: string;
    date_modified_gmt?: string;
    type?: string | 'simple' | 'variable' | 'grouped';
    status?: string;
    featured?: boolean;
    catalog_visibility?: string;
    description?: string;
    short_description?: string;
    sku?: string;
    price?: string;
    regular_price?: string;
    sale_price?: string;
    date_on_sale_from?: string;
    date_on_sale_from_gmt?: string;
    date_on_sale_to?: string;
    date_on_sale_to_gmt?: string;
    price_html?: string;
    on_sale?: boolean;
    purchasable?: boolean;
    total_sales?: number;
    virtual?: boolean;
    downloadable?: boolean;
    downloads?: any[];
    download_limit?: number;
    download_expiry?: number;
    external_url?: string;
    button_text?: string;
    tax_status?: string;
    tax_class?: string;
    manage_stock?: boolean;
    stock_quantity?: number;
    in_stock?: boolean;
    backorders?: string;
    backorders_allowed?: boolean;
    backordered?: boolean;
    sold_individually?: boolean;
    weight?: string | number;
    dimensions?: DimensionsWcInterface;
    shipping_required?: boolean;
    shipping_taxable?: boolean;
    shipping_class?: string;
    shipping_class_id?: number;
    reviews_allowed?: boolean;
    average_rating?: string;
    rating_count?: number;
    related_ids?: number[];
    upsell_ids?: number[];
    cross_sell_ids?: number[];
    parent_id?: number;
    purchase_note?: string;
    categories?: Partial<CategoryWcInterface>[];
    tags?: TagWcInterface[];
    images?: ImageWcInterface[];
    attributes?: AttributeWcInterface[];
    default_attributes?: any[];
    variations?: number[] | VariationWcInterface[];
    grouped_products?: any[];
    menu_order?: number;
    meta_data?: MetaDataWcInterface[];
    _links?: LinksWcInterface;
}
